src/main/java/pl/touk/sputnik/processor/findbugs/CollectorBugReporter.java
With current implementation I sometimes got FindBugs errors in wrong file. I found that lastObservedClass in CollectorBugReporter does not always match actual class with error but this class could be obtained from bugInstance.getPrimarySourceLineAnnotation().getClassName().
=> Fixed class name for FindBugs violation.

src/main/java/pl/touk/sputnik/Main.java, src/main/java/pl/touk/sputnik/configuration/GeneralOptionNotSupportedException.java, src/main/java/pl/touk/sputnik/connector/ConnectorFacade.java, src/main/java/pl/touk/sputnik/connector/ConnectorFacadeFactory.java, src/main/java/pl/touk/sputnik/connector/ConnectorType.java, src/main/java/pl/touk/sputnik/connector/gerrit/GerritFacade.java, src/main/java/pl/touk/sputnik/connector/stash/StashFacade.java, src/test/java/pl/touk/sputnik/connector/ConnectorFacadeFactoryTest.java, src/test/java/pl/touk/sputnik/connector/FacadeConfigUtil.java, src/test/java/pl/touk/sputnik/connector/gerrit/GerritFacadeHttpsTest.java, src/test/java/pl/touk/sputnik/connector/gerrit/GerritFacadeTest.java, src/test/java/pl/touk/sputnik/connector/stash/StashFacadeHttpsTest.java, src/test/java/pl/touk/sputnik/connector/stash/StashFacadeTest.java
- added tests for new option
- changed ConfigurationSetup.setUp to static to avoid creating instance that is not used
- changed connector types to enum
=> Warn when user wants to configure properties in way it is not fully supported

build.gradle
- this update contains support for LDAP and HTTP digest auth
=> update gerrit-rest-java-client to v0.8.1

src/main/java/pl/touk/sputnik/connector/stash/StashFacade.java, src/test/java/pl/touk/sputnik/connector/stash/StashFacadeTest.java
Stash returns Internal Server Error when pull request contatins files located in project root directory (without parent). The cause is slash at the beginning of file name. 
Log:
```
22:32:55.088 [main] INFO  p.t.s.connector.http.HttpConnector - Request 2: GET to http://localhost:7990/rest/api/1.0/projects/PROJ/repos/repo1/pull-requests/1/diff//build.gradle?contextLines=-1&srcPath=%2Fbuild.gradle&withComments=true
22:32:55.388 [main] INFO  p.t.s.connector.http.HttpConnector - Response 2: HTTP/1.1 500 Internal Server Error
22:32:55.394 [main] INFO  p.t.s.connector.http.HttpConnector - Entity 2: {"errors":[{"context":null,"message":"'/usr/bin/git diff -C --color=never -U10 --dst-prefix=dst:// --src-prefix=src:// 5f338d8f4c6a2784c600521f6eb1c9f9b1eef440 …
```
=> ReviewFile without starting slash in file name

build.gradle, src/test/java/pl/touk/sputnik/CatchException.java, src/test/java/pl/touk/sputnik/connector/gerrit/GerritFacadeExceptionTest.java, src/test/java/pl/touk/sputnik/connector/gerrit/GerritFacadeTest.java, src/test/java/pl/touk/sputnik/processor/findbugs/FindBugsProcessorTest.java, src/test/java/pl/touk/sputnik/processor/pmd/PmdProcessorTest.java
CatchException is not longer needed on Java 8, replaced it with custom implementation
=> java8 + custom catchException on lambdas

src/main/java/pl/touk/sputnik/connector/gerrit/GerritFacade.java, src/main/java/pl/touk/sputnik/processor/findbugs/CollectorBugReporter.java, src/main/java/pl/touk/sputnik/review/Comment.java, src/main/java/pl/touk/sputnik/review/Review.java, src/main/java/pl/touk/sputnik/review/ReviewFile.java
Sometimes FindBugs reports -1 as line number. Passing -1 as line number to Gerrit from Sputnik ends with exception. I've prepared a fix to convert negative line numbers from FindBugs to 0. Comments with line number 0 are treated as comments for entire file in Gerrit.
=> Negative line numbers from FindBugs converted to 0.

src/main/java/pl/touk/sputnik/processor/findbugs/FindBugsProcessor.java, src/main/java/pl/touk/sputnik/processor/pmd/PmdProcessor.java, src/test/java/pl/touk/sputnik/processor/findbugs/FindBugsProcessorTest.java, src/test/java/pl/touk/sputnik/processor/pmd/PmdProcessorTest.java
When there are no files to review in commit (based on extension matching) for FindBugs od PMD processors, there is exception thrown and logged in Sputnik logs:
```
13:10:47.721 [main] ERROR p.t.s.p.findbugs.FindBugsProcessor - FindBugs processing error
java.io.IOException: No files to analyze could be opened
at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:276) ~[findbugs-3.0.0.jar:na]
at pl.touk.sputnik.processor.findbugs.FindBugsProcessor.process(FindBugsProcessor.java:29) ~[sputnik-1.4.0.jar:1.4.0]
at pl.touk.sputnik.engine.ReviewRunner.review(ReviewRunner.java:24) [sputnik-1.4.0.jar:1.4.0]
at pl.touk.sputnik.engine.Engine.run(Engine.java:33) [sputnik-1.4.0.jar:1.4.0]
at pl.touk.sputnik.Main.main(Main.java:37) [sputnik-1.4.0.jar:1.4.0]
13:10:47.722 [main] ERROR …
```
=> No exception thrown when there are no files to review for FindBugs and PMD.

build.gradle, src/main/java/pl/touk/sputnik/configuration/GeneralOption.java, src/main/java/pl/touk/sputnik/processor/jslint/JsLintProcessor.java, src/test/java/pl/touk/sputnik/processor/jslint/JsLintProcessorTest.java, src/test/resources/js/test.js, src/test/resources/jshint/jshint.json, src/test/resources/jslint/jslint.properties, src/test/resources/jslint/sputnik/noConfigurationFile.properties, src/test/resources/jslint/sputnik/withConfigurationFile.properties
This commit added possibility to configure options for JSLint processor using property file. Currently such configuration is not possible although JSLInt API allows this.
I have also added new repo entry in the build file since mavenCentral() seems to download artifiacts from other repository url then "http://central.maven.org/maven2".
=> Added support for configuring JSLint

src/main/java/pl/touk/sputnik/processor/findbugs/FindBugsProcessor.java, src/test/java/pl/touk/sputnik/processor/findbugs/FindBugsProcessorTest.java
(Also see https://github.com/TouK/sputnik/issues/69)
The change to global problems collection (https://github.com/TouK/sputnik/commit/75b30e12a1ec6378eaa29853dc539e50ea7bd37d) caused Sputnik to report a problem in cases where FindBugs had no files to check, because FindBugs by default throws IOException in that case. Since FindBugs only checks Java files, this can occur if a commit or pull request includes changes to build files, properties files, or documentation, which does not seem like an error condition.
The previous revision of the FindBugs processor swallowed IOException in this case. Fortunately, FindBugs has a flag that can be set to avoid the exception instead, which is a little cleaner. The result is an empty review.
=> Avoid reporting error on Findbugs empty review

src/test/java/pl/touk/sputnik/review/locator/MavenBuildDirLocatorTest.java
Initializing ConfigurationHolder in MavenBuildDirLocatorTest should fix NPE in this test (https://travis-ci.org/TouK/sputnik/builds/56576263). Solution similar to one used in ReviewInputBuilderTest.
=> Initializing ConfigurationHolder in MavenBuildDirLocatorTest

README.md, contrib/stash-execute.sh
- allows to pass all arguments to script without the need of modifying this script
- allows to pass Stash username, Stash password and branch (we can use any plain value or bamboo variable)
- you can pass URL to sputnik distribution
- stash_host, project_key, repository_slug are read from `sputnik.properties`
- all checks are done at the beginning (fail-fast)
=> Passing arguments to stash-execute.sh script

src/main/resources/example.properties
According to https://github.com/TouK/sputnik/blob/master/src/main/java/pl/touk/sputnik/configuration/GeneralOption.java#L49 property key is `scalastyle.configurationFile`
=> Updated key in example.properties storing ScalaStyle configuration file

src/main/java/pl/touk/sputnik/processor/sonar/SonarResultParser.java
The getIssueFilePath was also resolving components modules
which are also components), to complete file path.
But only components with "path" were added to components list.
Therefore, if a module didn't have "path". It was not added.
No check was done on whether it was found or not => NPE
FIX : add all components. Components without "path" will have empty
path attribute.
=> Fix NPE when running sonar

src/main/java/pl/touk/sputnik/processor/codenarc/CodeNarcProcessor.java, src/main/java/pl/touk/sputnik/processor/codenarc/CodeNarcRunnerBuilder.java, src/test/java/pl/touk/sputnik/processor/codenarc/CodeNarcProcessorTest.java
The problem occured when all files to review should be filtered out (all
had wrong extension). And indeed it was happening when include file
list was created, but not before start CodeNarc. When CodeNarc obtains
empty file list, then it includes to analyze all files from base directory.
=> Fix passing empty inlude file list to CodeNarc

src/main/java/pl/touk/sputnik/connector/stash/StashFacade.java, src/test/java/pl/touk/sputnik/connector/stash/StashFacadeTest.java, src/test/resources/json/stash-changes-deleted-file.json
Deleted files in Stash should be excluded. Without this you will get such comments:
> Total 2 violations found. There is a problem with PMD: RuntimeException: File App.java doesn't exist
or
> [Checkstyle] ERROR: File not found!
=> Exclude deleted files from analysis

contrib/stash-execute.sh
stash-execute.sh does not work for branches with accented character in name. `json.load` translate strings into unicode (https://docs.python.org/2/library/json.html#json-to-py-table) and comparison between str and unicode fails (`pr["fromRef"]["displayId"] == "$current_branch"`).
=> Unicode support for branch name in stash-execute.sh

build.gradle, src/main/java/pl/touk/sputnik/processor/checkstyle/CheckstyleProcessor.java
Checkstyle needs to be updated to version 6.14.1 because there were new rules and in current version the most recent google style did not work.
=> Checkstyle bumped to version 6.14.1

build.gradle, src/main/java/pl/touk/sputnik/engine/ProcessorBuilder.java, src/main/java/pl/touk/sputnik/processor/ReviewProcessorFactory.java, src/main/java/pl/touk/sputnik/processor/checkstyle/CheckstyleReviewProcessorFactory.java, src/main/java/pl/touk/sputnik/processor/codenarc/NodeCardReviewProcessorFactory.java, src/main/java/pl/touk/sputnik/processor/findbugs/FindbugsReviewProcessorFactory.java, src/main/java/pl/touk/sputnik/processor/jshint/JsHintReviewProcessorFactory.java, src/main/java/pl/touk/sputnik/processor/jslint/JsLintReviewProcessorFactory.java, src/main/java/pl/touk/sputnik/processor/pmd/PmdReviewProcessorFactory.java, src/main/java/pl/touk/sputnik/processor/scalastyle/ScalastyleReviewProcessorFactory.java, src/main/java/pl/touk/sputnik/processor/sonar/SonarReviewProcessorFactory.java, src/main/java/pl/touk/sputnik/processor/sonar/SonarRunner.java, src/main/java/pl/touk/sputnik/processor/sonar/SonarRunnerBuilder.java, src/main/resources/META-INF/services/pl.touk.sputnik.processor.ReviewProcessorFactory, src/test/java/pl/touk/sputnik/processor/checkstyle/CheckstyleReviewProcessorFactoryTest.java, src/test/java/pl/touk/sputnik/processor/codenarc/NodeCardReviewProcessorFactoryTest.java, src/test/java/pl/touk/sputnik/processor/findbugs/FindbugsReviewProcessorFactoryTest.java, src/test/java/pl/touk/sputnik/processor/jshint/JsHintReviewProcessorFactoryTest.java, src/test/java/pl/touk/sputnik/processor/jslint/JsLintReviewProcessorFactoryTest.java, src/test/java/pl/touk/sputnik/processor/pmd/PmdReviewProcessorFactoryTest.java, src/test/java/pl/touk/sputnik/processor/scalastyle/ScalastyleReviewProcessorFactoryTest.java, src/test/java/pl/touk/sputnik/processor/sonar/SonarReviewProcessorFactoryTest.java, src/test/java/pl/touk/sputnik/processor/sonar/SonarRunnerTest.java
First shot for an implementation based on the Java ServiceLoader mechanism.
=> Implementation of #113 Plugin Facility for Sputnik Processors

src/main/java/pl/touk/sputnik/processor/sonar/SonarRunner.java, src/test/java/pl/touk/sputnik/processor/sonar/SonarRunnerTest.java
Currently you are writing the props to a safe
copy (clone()) of the actual property list and
thus the properties you are adding
are never written into the actual
instance properties.
Using the proper method for adding the properties
fixes this
Fixes issue:  #136
=> Fix sonar properties transfer

src/main/java/pl/touk/sputnik/engine/visitor/SummaryMessageVisitor.java, src/test/java/pl/touk/sputnik/engine/visitor/SummaryMessageVisitorTest.java
Now a summary message for a review with one violation is "Total 1 violation found" instead of "Total 1 violations found".
=> Summary message with singular noun

build.gradle
This ensures compatibility with Gerrit 2.12.2.
=> Update Gerrit Rest API lib to 0.8.8

build.gradle
previous version of PMD had some bug that causes NPE 
`09:09:52.265 [main] ERROR p.t.s.processor.pmd.PmdProcessor - PMD processing error. Something wrong with configuration or analyzed files are not in workspace.
java.util.ConcurrentModificationException: null
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[na:1.8.0_60]
at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[na:1.8.0_60]
at net.sourceforge.pmd.RuleSet.removeDysfunctionalRules(RuleSet.java:530) ~[pmd-core-5.4.1.jar:na]
at net.sourceforge.pmd.RuleSets.removeDysfunctionalRules(RuleSets.java:203) ~[pmd-core-5.4.1.jar:na]
at net.sourceforge.pmd.PMD.removeBrokenRules(PMD.java:160) ~[pmd-core-5.4.1.jar:na]
at net.sourceforge.pmd.PMD.setupReport(PMD.java:139) ~[pmd-core-5.4.1.jar:na]
at …
=> PMD version bumped to 5.5.2, no NPE in certain cases

src/main/java/pl/touk/sputnik/processor/scalastyle/ScalastyleProcessor.java
Sending -1 results in:
```
07:51:17.135 [main] INFO  p.t.s.e.v.score.ScoreAlwaysPass - Adding static passing score {Code-Review=1} to review
Exception in thread "main" pl.touk.sputnik.connector.gerrit.GerritException: Error when setting review
at pl.touk.sputnik.connector.gerrit.GerritFacade.publish(GerritFacade.java:71)
at pl.touk.sputnik.engine.Engine.run(Engine.java:47)
at pl.touk.sputnik.Main.main(Main.java:36)
Caused by: com.urswolfer.gerrit.client.rest.http.HttpStatusException: Request not successful. Message: Bad Request. Status-Code: 400. Content: negative line number -1 not allowed on test/Point.scala.
at com.urswolfer.gerrit.client.rest.http.GerritRestClient.checkStatusCode(GerritRestClient.java:370)
at com.urswolfer.gerrit.client.rest.http.GerritRestClient.request(GerritRestClie …
```
=> Do not send -1 as line number from scala style

src/main/java/pl/touk/sputnik/processor/pylint/PylintResultParser.java, src/main/java/pl/touk/sputnik/processor/pylint/json/PylintMessage.java, src/test/java/pl/touk/sputnik/processor/pylint/PylintResultParserTest.java, src/test/resources/pylint/output-with-message-id.txt
This commit fixes issue #187, by optionally including the message-id in the violation message. This message-id was added in Pylint 1.8 and crashed Sputnik.
=> Support Pylint 1.8 message-id

build.gradle, src/main/java/pl/touk/sputnik/configuration/GeneralOption.java, src/main/java/pl/touk/sputnik/connector/ConnectorFacadeFactory.java, src/main/java/pl/touk/sputnik/connector/ConnectorType.java, src/main/java/pl/touk/sputnik/connector/Connectors.java, src/main/java/pl/touk/sputnik/connector/local/LocalFacade.java, src/main/java/pl/touk/sputnik/connector/local/LocalFacadeBuilder.java, src/main/java/pl/touk/sputnik/connector/local/LocalFacadeOutput.java, src/main/java/pl/touk/sputnik/review/ReviewFile.java, src/test/java/pl/touk/sputnik/connector/local/LocalFacadeTest.java
Fixes #195 
Runs analysis tools on the HEAD of the local git repository and reports
to the log.
Allows someone to check for any comments before pushing to
Gerrit/Gitlab.
=> Add "local" connector type

src/main/java/pl/touk/sputnik/configuration/GeneralOption.java, src/main/java/pl/touk/sputnik/processor/eslint/ESLintExecutor.java, src/main/java/pl/touk/sputnik/processor/eslint/ESLintProcessor.java, src/main/java/pl/touk/sputnik/processor/eslint/ESLintResultParser.java
- Allow specifying the eslint executable path via the setting
GeneralOption.ESLINT_EXECUTABLE. This is useful when running a
non-global install of eslint.
- When specifying an alternative folder, the plugins used by ESLint
can't be found, as ESLint searches in its working directory. It can
search in a different directory, specified by https://eslint.org/
docs/user-guide/command-line-interface#--resolve-plugins-relative-to.
So, we also allow configuring this folder through
GeneralOption.ESLINT_PLUGINS_FOLDER.
- Do not crash on ESLint's unknown fields in JSON output.
Closes #216.
=> Extend ESLint functionality

build.gradle
This is the highest release of gerrit-rest-java-client atm.
Resolves multiple issues fixed in gerrit-rest-java-client.
=> Bump gerrit-rest-java-client to 0.9.3

build.gradle
- httpclient:4.5.8 is included with gerrit-rest-java-client
- commons-cli:1.4 is included with checkstyle
(1.2 does not even have the DefaultParser that is used for the CLI)
These versions are now explicitly defined, so build won't fail
if the first level dependencies won't rely on them anymore.
=> Bump dependency versions that are grabbed transitively

src/test/java/pl/touk/sputnik/processor/checkstyle/CheckstyleProcessorTest.java, src/test/resources/checkstyle/checkstyle.xml
Tests failed on Windows systems as the test file uses LF ending.
=> Use explicit checkstyle configuration for tests

src/main/java/pl/touk/sputnik/configuration/GeneralOption.java, src/main/java/pl/touk/sputnik/connector/gerrit/GerritFacade.java, src/main/java/pl/touk/sputnik/connector/gerrit/GerritFacadeBuilder.java, src/main/java/pl/touk/sputnik/connector/gerrit/GerritOptions.java, src/test/java/pl/touk/sputnik/connector/gerrit/GerritFacadeBuilderTest.java, src/test/java/pl/touk/sputnik/connector/gerrit/GerritFacadeExceptionTest.java, src/test/java/pl/touk/sputnik/connector/gerrit/GerritFacadeTest.java, src/test/java/pl/touk/sputnik/connector/gerrit/GerritOptionsTest.java, src/test/java/pl/touk/sputnik/connector/gerrit/ReviewInputBuilderTest.java
Allow usage of Gerrit HTTP password tokens (#220)
URL encode changeId when creating GerritPatchset (#221)
Support gerrit configuration to omit duplicate comments (#108)
=> Improve Gerrit connector usability

src/main/java/pl/touk/sputnik/configuration/GeneralOption.java, src/main/java/pl/touk/sputnik/processor/spotbugs/SpotBugsProcessor.java, src/test/java/pl/touk/sputnik/processor/spotbugs/SpotBugsProcessorTest.java, src/test/resources/spotbugs/spotbugs-config.properties
Some detector can be configured with these properties, also debugging
can be turned on if needed.
The option name is the same as the one that is used in Spotbugs
itself ('findbugs.loadPropertiesFrom')
=> Allow loading of Spotbugs properties from external file

src/main/java/pl/touk/sputnik/processor/checkstyle/CheckstyleProcessor.java, src/test/java/pl/touk/sputnik/processor/checkstyle/CheckstyleProcessorTest.java, src/test/resources/checkstyle/checkstyle-with-suppressions.xml, src/test/resources/checkstyle/suppressions.xml
This is a half-official property, that is not set by Checkstyle itself
by default, but provided by IDE tools for Eclipse and IDEA.
In order to use the same configuration for IDE and Sputnik, it's useful
to have this property set here also
=> Set config_loc property for Checkstyle

README.md
- github rendered the tildes in the changeId with strikethrough
- made the description more compact
=> Adjust gerrit change id description in the readme
